services:
  devcontainer:
    container_name: quizmaster-backend
    image: maven:3.8.5-openjdk-17
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      BACKEND_DB_USER: dbuser
      BACKEND_DB_PASSWORD: dbpassword
      BACKEND_PORT: 8080
      FRONTEND_URL: http://localhost:4200
      SPRING_PROFILE: local
      APP_VERSION_FROM_POM_XML: 1.0.0
    ports:
      - "8080:8080"
    volumes:
      - ..:/project