services:
  run:
    container_name: quizmaster-backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAVA_VERSION: 17.0.4-tem
        MAVEN_VERSION: 3.8.6
    environment:
      USER: docker
      SPRING_PROFILE: local
      # environment variables to be used by the application-local.yml
      BACKEND_DB_USER: dbuser
      BACKEND_DB_PASSWORD: dbpassword
      BACKEND_PORT: 8080
      FRONTEND_URL: http://localhost:4200
    ports:
      - "8080:8080"
    volumes:
      - ..:/home/docker/project
      - ~/.m2:/home/docker/.m2